### ISSUE TITLE
GUI Up/Down arrows not working

### ISSUE THREAD

**Issue by astronomerdave** [CaltechOpticalObservatories/NGPS#7] opened 2023-05-19 19:05 UTC
Selecting a target in the list highlights it yellow, but using the keyboard arrow keys do not traverse the list 
Any arrow key makes the highlighted bar jump to the top of the list.

**Comment by jenniferwillow** [comment] 2023-05-19 19:12
Hi Dave,
     I spent 5 hours working on this issue and I wasn’t able to fix it.  I suspect the “fix” I used to eliminate multiple yellow lines is making it impossible to use the arrow keys.  I’ll try again next week.
Jennifer

On May 19, 2023, at 12:05 PM, David Hale ***@***.******@***.***>> wrote:



Selecting a target in the list highlights it yellow, but using the keyboard arrow keys do not traverse the list
Any arrow key makes the highlighted bar jump to the top of the list.

**Comment by chazshapiro** [comment] 2024-03-01 18:23
Pinging this issue

**Comment by chazshapiro** [comment] 2024-07-24 18:07
Fixed in NGPSFrame.java

The issue is that the native state of `main_editor_table` (a JTable) was out of sync with the NGPSFrame class.  For example, I created a new action for the DOWN key:

```
class DownKeyAction extends AbstractAction{
    @Override
    public void actionPerformed(ActionEvent e){
        JTable tbl = (JTable)e.getSource();
        tbl.requestFocus();
        if(selected_table_row < tbl.getRowCount()-1){
            tbl.changeSelection(selected_table_row+1, tbl.getSelectedColumn(), false, false);        
        }
    }
}
```

where I had to use `selected_table_row` instead of `tbl.getSelectedRow()` because the latter was always -1.

This action is then used to override the JTable:

```
 public void initializeMainTable(){
   main_editor_table =  constructTable();
   main_editor_table.setModel(dbms.myTargetDBMSTableModel);
   initializeTableModel(main_editor_table,dbms.myTargetDBMSTableModel);

  // CHAZ kludge to fix arrow key navigation in main table
  KeyStroke downkey = KeyStroke.getKeyStroke(KeyEvent.VK_DOWN, 0)  ; 
  KeyStroke upkey = KeyStroke.getKeyStroke(KeyEvent.VK_UP, 0)  ; 
  KeyStroke enterkey = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0)  ; 
  main_editor_table.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(downkey, "downkey");
  main_editor_table.getActionMap().put("downkey", new DownKeyAction());
  main_editor_table.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(upkey, "upkey");
  main_editor_table.getActionMap().put("upkey", new UpKeyAction());
  main_editor_table.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(enterkey, "enterkey"); //ENTER was causing selection jump to top row
  main_editor_table.getActionMap().put("enterkey", null );
```

This is a kludgey fix.  JTables are able to keep track of rows and columns on their own.  It would be better to refactor to remove unnecessary copies of table state parameters.  However, usage of `selected_table_row` looks prevalent in the code.

**Closed by chazshapiro** 2024-07-24 18:07 UTC
Labels: bug, PRIORITY ITEM
